[package]
name = "xnet"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
ratatui = "0.30.0"
crossterm = "0.27"
tokio = { version = "1.37", features = ["full"] }
netdev = "0.40.0"
pnet = "0.35.0"